/// BSTI 16개 피부유형 데이터 (타입별 객체 · child 구조).
///
/// 각 [BstiSkinType]이 자신의 권장/기피 성분을 [BstiTypeIngredient] child로 직접 품는다.
/// 수식어(멀티벤핏 등)는 [BstiTypeIngredient.isMultibenefit]에 담긴다.
/// 성분의 실제 이름·역할은 [bsti_dataset.dart]의 `kBstiIngredients`에서 id로 조회.
///
/// 백엔드 없이 프론트에서 이 맵만 참조해 결과를 구성한다.
library;

import 'bsti_models.dart';

/// 코드(예: 'OSPW') → 피부유형. (bsti_skin_types + bsti_type_ingredients: 16개)
const Map<String, BstiSkinType> kBstiSkinTypes = {
  'OSPW': BstiSkinType(
    code: 'OSPW',
    personaName: '진정 먼저 챙기는 풀코스 케어 고양이',
    tagline: '진정·선크림으로 기초를 다진 뒤 미백→안티에이징 순서로 하나씩 도전.',
    oil: 'O',
    sensitivity: 'S',
    pigment: 'P',
    aging: 'W',
    summary:
        '지성 · 민감 · 색소 · 주름 피부. 피지 조절을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 레티놀·비타민C로 콜라겐 자극이 핵심.',
    careOrder: ['진정·장벽', '선크림', '미백', '안티에이징'],
    sunscreenId: 'tint',
    recommend: [
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sal', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'aze', isMultibenefit: true, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'cica', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'bisa', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'vcd', isMultibenefit: true, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'retal', isMultibenefit: false, sortOrder: 8),
      BstiTypeIngredient(ingredientId: 'pept', isMultibenefit: false, sortOrder: 9),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'fragrance', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'essoil', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'bpo', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'glycolic', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'reti_hi', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'chem_filter', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'coconut', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'ipm', isMultibenefit: false, sortOrder: 8),
      BstiTypeIngredient(ingredientId: 'lanolin', isMultibenefit: false, sortOrder: 9),
    ],
  ),
  'OSPT': BstiSkinType(
    code: 'OSPT',
    personaName: '피지 잡고 순하게 톤업하는 고양이',
    tagline: '유분 조절 + 나이아신아마이드 같은 순한 미백으로 잡티 케어.',
    oil: 'O',
    sensitivity: 'S',
    pigment: 'P',
    aging: 'T',
    summary:
        '지성 · 민감 · 색소 · 탱탱 피부. 피지 조절을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 항산화로 노화 예방이 핵심.',
    careOrder: ['진정·장벽', '선크림', '미백'],
    sunscreenId: 'tint',
    recommend: [
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sal', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'aze', isMultibenefit: true, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'cica', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'bisa', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'vcd', isMultibenefit: true, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'toco', isMultibenefit: false, sortOrder: 8),
      BstiTypeIngredient(ingredientId: 'feru', isMultibenefit: false, sortOrder: 9),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'fragrance', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'essoil', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'bpo', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'glycolic', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'reti_hi', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'chem_filter', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'coconut', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'ipm', isMultibenefit: false, sortOrder: 8),
      BstiTypeIngredient(ingredientId: 'lanolin', isMultibenefit: false, sortOrder: 9),
    ],
  ),
  'OSNW': BstiSkinType(
    code: 'OSNW',
    personaName: '장벽부터 쌓고 주름 대비하는 고양이',
    tagline: '장벽을 튼튼히 쌓은 뒤 저자극 레티놀로 노화 대비.',
    oil: 'O',
    sensitivity: 'S',
    pigment: 'N',
    aging: 'W',
    summary:
        '지성 · 민감 · 비색소 · 주름 피부. 피지 조절을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 자외선차단 예방, 레티놀·비타민C로 콜라겐 자극이 핵심.',
    careOrder: ['진정·장벽', '선크림', '안티에이징'],
    sunscreenId: 'mineralGel',
    recommend: [
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sal', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'aze', isMultibenefit: true, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'cica', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'bisa', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'retal', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'pept', isMultibenefit: false, sortOrder: 8),
      BstiTypeIngredient(ingredientId: 'vcd', isMultibenefit: true, sortOrder: 9),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'fragrance', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'essoil', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'bpo', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'glycolic', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'reti_hi', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'chem_filter', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'coconut', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'ipm', isMultibenefit: false, sortOrder: 8),
      BstiTypeIngredient(ingredientId: 'lanolin', isMultibenefit: false, sortOrder: 9),
    ],
  ),
  'OSNT': BstiSkinType(
    code: 'OSNT',
    personaName: '수분만 챙기는 속예민 물광 고양이',
    tagline: '가벼운 보습과 장벽 케어, 제품은 적게.',
    oil: 'O',
    sensitivity: 'S',
    pigment: 'N',
    aging: 'T',
    summary:
        '지성 · 민감 · 비색소 · 탱탱 피부. 피지 조절을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 자외선차단 예방, 항산화로 노화 예방이 핵심.',
    careOrder: ['진정·장벽', '선크림'],
    sunscreenId: 'mineralGel',
    recommend: [
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sal', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'aze', isMultibenefit: true, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'cica', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'bisa', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'toco', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'feru', isMultibenefit: false, sortOrder: 8),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'fragrance', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'essoil', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'bpo', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'glycolic', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'reti_hi', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'chem_filter', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'coconut', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'ipm', isMultibenefit: false, sortOrder: 8),
      BstiTypeIngredient(ingredientId: 'lanolin', isMultibenefit: false, sortOrder: 9),
    ],
  ),
  'ORPW': BstiSkinType(
    code: 'ORPW',
    personaName: '미백·주름 풀가동하는 강철 고양이',
    tagline: '튼튼한 피부라 레티놀+비타민C 적극 활용 가능.',
    oil: 'O',
    sensitivity: 'R',
    pigment: 'P',
    aging: 'W',
    summary:
        '지성 · 저항 · 색소 · 주름 피부. 피지 조절을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 레티놀·비타민C로 콜라겐 자극이 핵심.',
    careOrder: ['피지·모공', '선크림', '미백', '안티에이징'],
    sunscreenId: 'tint',
    recommend: [
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sal', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'zinc', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'txa', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'vc', isMultibenefit: true, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'arb', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'reti', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'pept', isMultibenefit: false, sortOrder: 8),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'coconut', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ipm', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'lanolin', isMultibenefit: false, sortOrder: 3),
    ],
  ),
  'ORPT': BstiSkinType(
    code: 'ORPT',
    personaName: '피지·잡티 잡는 탄탄 톤업 고양이',
    tagline: '유분 조절 + 미백 집중, 선크림으로 재발 방지.',
    oil: 'O',
    sensitivity: 'R',
    pigment: 'P',
    aging: 'T',
    summary:
        '지성 · 저항 · 색소 · 탱탱 피부. 피지 조절을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 항산화로 노화 예방이 핵심.',
    careOrder: ['피지·모공', '선크림', '미백'],
    sunscreenId: 'tint',
    recommend: [
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sal', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'zinc', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'txa', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'vc', isMultibenefit: true, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'arb', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'toco', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'feru', isMultibenefit: false, sortOrder: 8),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'coconut', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ipm', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'lanolin', isMultibenefit: false, sortOrder: 3),
    ],
  ),
  'ORNW': BstiSkinType(
    code: 'ORNW',
    personaName: '안티에이징에 올인하는 광채 고양이',
    tagline: '자극 걱정 없이 레티놀·펩타이드 마음껏.',
    oil: 'O',
    sensitivity: 'R',
    pigment: 'N',
    aging: 'W',
    summary:
        '지성 · 저항 · 비색소 · 주름 피부. 피지 조절을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 자외선차단 예방, 레티놀·비타민C로 콜라겐 자극이 핵심.',
    careOrder: ['피지·모공', '선크림', '안티에이징'],
    sunscreenId: 'organic',
    recommend: [
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sal', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'zinc', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'reti', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'pept', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'vc', isMultibenefit: true, sortOrder: 6),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'coconut', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ipm', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'lanolin', isMultibenefit: false, sortOrder: 3),
    ],
  ),
  'ORNT': BstiSkinType(
    code: 'ORNT',
    personaName: '기본만으로 완성되는 꿀피부 고양이',
    tagline: '세안·보습·선크림 기본 루틴이면 충분.',
    oil: 'O',
    sensitivity: 'R',
    pigment: 'N',
    aging: 'T',
    summary:
        '지성 · 저항 · 비색소 · 탱탱 피부. 피지 조절을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 자외선차단 예방, 항산화로 노화 예방이 핵심.',
    careOrder: ['피지·모공', '선크림'],
    sunscreenId: 'organic',
    recommend: [
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sal', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'zinc', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'toco', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'feru', isMultibenefit: false, sortOrder: 5),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'coconut', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ipm', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'lanolin', isMultibenefit: false, sortOrder: 3),
    ],
  ),
  'DSPW': BstiSkinType(
    code: 'DSPW',
    personaName: '장벽부터 차근차근 쌓는 종합케어 고양이',
    tagline: '보습·장벽 최우선, 미백·안티에이징은 순한 것부터 천천히.',
    oil: 'D',
    sensitivity: 'S',
    pigment: 'P',
    aging: 'W',
    summary:
        '건성 · 민감 · 색소 · 주름 피부. 장벽 보습을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 레티놀·비타민C로 콜라겐 자극이 핵심.',
    careOrder: ['진정·장벽', '선크림', '미백', '안티에이징'],
    sunscreenId: 'tintCream',
    recommend: [
      BstiTypeIngredient(ingredientId: 'cera', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ha', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'cica', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'bisa', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'aze', isMultibenefit: true, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'vcd', isMultibenefit: true, sortOrder: 8),
      BstiTypeIngredient(ingredientId: 'retal', isMultibenefit: false, sortOrder: 9),
      BstiTypeIngredient(ingredientId: 'pept', isMultibenefit: false, sortOrder: 10),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'fragrance', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'essoil', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'bpo', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'glycolic', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'reti_hi', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'chem_filter', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'alcohol_hi', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'sls', isMultibenefit: false, sortOrder: 8),
    ],
  ),
  'DSPT': BstiSkinType(
    code: 'DSPT',
    personaName: '보습 위에 미백 얹는 예민 진정 고양이',
    tagline: '진정+보습으로 바탕을 만들고 저자극 미백 추가.',
    oil: 'D',
    sensitivity: 'S',
    pigment: 'P',
    aging: 'T',
    summary:
        '건성 · 민감 · 색소 · 탱탱 피부. 장벽 보습을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 항산화로 노화 예방이 핵심.',
    careOrder: ['진정·장벽', '선크림', '미백'],
    sunscreenId: 'tintCream',
    recommend: [
      BstiTypeIngredient(ingredientId: 'cera', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ha', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'cica', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'bisa', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'aze', isMultibenefit: true, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'vcd', isMultibenefit: true, sortOrder: 8),
      BstiTypeIngredient(ingredientId: 'toco', isMultibenefit: false, sortOrder: 9),
      BstiTypeIngredient(ingredientId: 'feru', isMultibenefit: false, sortOrder: 10),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'fragrance', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'essoil', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'bpo', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'glycolic', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'reti_hi', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'chem_filter', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'alcohol_hi', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'sls', isMultibenefit: false, sortOrder: 8),
    ],
  ),
  'DSNW': BstiSkinType(
    code: 'DSNW',
    personaName: '수분으로 주름 늦추는 레이어링 고양이',
    tagline: '히알루론산+세라마이드 레이어링, 안티에이징은 펩타이드로.',
    oil: 'D',
    sensitivity: 'S',
    pigment: 'N',
    aging: 'W',
    summary:
        '건성 · 민감 · 비색소 · 주름 피부. 장벽 보습을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 자외선차단 예방, 레티놀·비타민C로 콜라겐 자극이 핵심.',
    careOrder: ['진정·장벽', '선크림', '안티에이징'],
    sunscreenId: 'mineral',
    recommend: [
      BstiTypeIngredient(ingredientId: 'cera', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ha', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'cica', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'bisa', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'retal', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'pept', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'vcd', isMultibenefit: true, sortOrder: 8),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'fragrance', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'essoil', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'bpo', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'glycolic', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'reti_hi', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'chem_filter', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'alcohol_hi', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'sls', isMultibenefit: false, sortOrder: 8),
    ],
  ),
  'DSNT': BstiSkinType(
    code: 'DSNT',
    personaName: '보습 하나로 빛나는 미니멀 고양이',
    tagline: '자극 줄이고 보습만 잘해도 충분.',
    oil: 'D',
    sensitivity: 'S',
    pigment: 'N',
    aging: 'T',
    summary:
        '건성 · 민감 · 비색소 · 탱탱 피부. 장벽 보습을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 자외선차단 예방, 항산화로 노화 예방이 핵심.',
    careOrder: ['진정·장벽', '선크림'],
    sunscreenId: 'mineral',
    recommend: [
      BstiTypeIngredient(ingredientId: 'cera', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ha', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'cica', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'bisa', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'toco', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'feru', isMultibenefit: false, sortOrder: 7),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'fragrance', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'essoil', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'bpo', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'glycolic', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'reti_hi', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'chem_filter', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'alcohol_hi', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'sls', isMultibenefit: false, sortOrder: 8),
    ],
  ),
  'DRPW': BstiSkinType(
    code: 'DRPW',
    personaName: '보습 깔고 잡티·주름 공략하는 전략 고양이',
    tagline: '보습 베이스 위에 레티놀·비타민C 활용.',
    oil: 'D',
    sensitivity: 'R',
    pigment: 'P',
    aging: 'W',
    summary:
        '건성 · 저항 · 색소 · 주름 피부. 장벽 보습을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 레티놀·비타민C로 콜라겐 자극이 핵심.',
    careOrder: ['보습·장벽', '선크림', '미백', '안티에이징'],
    sunscreenId: 'tintCream',
    recommend: [
      BstiTypeIngredient(ingredientId: 'cera', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ha', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'txa', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'vc', isMultibenefit: true, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'arb', isMultibenefit: false, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'reti', isMultibenefit: false, sortOrder: 8),
      BstiTypeIngredient(ingredientId: 'pept', isMultibenefit: false, sortOrder: 9),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'alcohol_hi', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sls', isMultibenefit: false, sortOrder: 2),
    ],
  ),
  'DRPT': BstiSkinType(
    code: 'DRPT',
    personaName: '선크림이 무기인 차분한 톤업 고양이',
    tagline: '보습+미백 투트랙, 자외선 차단이 핵심.',
    oil: 'D',
    sensitivity: 'R',
    pigment: 'P',
    aging: 'T',
    summary:
        '건성 · 저항 · 색소 · 탱탱 피부. 장벽 보습을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 항산화로 노화 예방이 핵심.',
    careOrder: ['보습·장벽', '선크림', '미백'],
    sunscreenId: 'tintCream',
    recommend: [
      BstiTypeIngredient(ingredientId: 'cera', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ha', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'squa', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'niac', isMultibenefit: true, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'txa', isMultibenefit: false, sortOrder: 6),
      BstiTypeIngredient(ingredientId: 'vc', isMultibenefit: true, sortOrder: 7),
      BstiTypeIngredient(ingredientId: 'arb', isMultibenefit: false, sortOrder: 8),
      BstiTypeIngredient(ingredientId: 'toco', isMultibenefit: false, sortOrder: 9),
      BstiTypeIngredient(ingredientId: 'feru', isMultibenefit: false, sortOrder: 10),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'alcohol_hi', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sls', isMultibenefit: false, sortOrder: 2),
    ],
  ),
  'DRNW': BstiSkinType(
    code: 'DRNW',
    personaName: '항산화로 시간 붙잡는 맑은 피부 고양이',
    tagline: '보습에 항산화·콜라겐 케어를 더해 주름 속도 늦추기.',
    oil: 'D',
    sensitivity: 'R',
    pigment: 'N',
    aging: 'W',
    summary:
        '건성 · 저항 · 비색소 · 주름 피부. 장벽 보습을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 자외선차단 예방, 레티놀·비타민C로 콜라겐 자극이 핵심.',
    careOrder: ['보습·장벽', '선크림', '안티에이징'],
    sunscreenId: 'basic',
    recommend: [
      BstiTypeIngredient(ingredientId: 'cera', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ha', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'reti', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'pept', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'vc', isMultibenefit: true, sortOrder: 6),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'alcohol_hi', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sls', isMultibenefit: false, sortOrder: 2),
    ],
  ),
  'DRNT': BstiSkinType(
    code: 'DRNT',
    personaName: '수분 충전만으로 완성되는 저관리 꿀피부 고양이',
    tagline: '보습·선크림 루틴이면 끝.',
    oil: 'D',
    sensitivity: 'R',
    pigment: 'N',
    aging: 'T',
    summary:
        '건성 · 저항 · 비색소 · 탱탱 피부. 장벽 보습을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 자외선차단 예방, 항산화로 노화 예방이 핵심.',
    careOrder: ['보습·장벽', '선크림'],
    sunscreenId: 'basic',
    recommend: [
      BstiTypeIngredient(ingredientId: 'cera', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'ha', isMultibenefit: false, sortOrder: 2),
      BstiTypeIngredient(ingredientId: 'panth', isMultibenefit: false, sortOrder: 3),
      BstiTypeIngredient(ingredientId: 'squa', isMultibenefit: false, sortOrder: 4),
      BstiTypeIngredient(ingredientId: 'toco', isMultibenefit: false, sortOrder: 5),
      BstiTypeIngredient(ingredientId: 'feru', isMultibenefit: false, sortOrder: 6),
    ],
    avoid: [
      BstiTypeIngredient(ingredientId: 'alcohol_hi', isMultibenefit: false, sortOrder: 1),
      BstiTypeIngredient(ingredientId: 'sls', isMultibenefit: false, sortOrder: 2),
    ],
  ),
};
